### ISSUE TITLE
Add KiwiHawk as collaborator for Trainwreck's sea block mods on factorio mod portal

### ISSUE THREAD

**Issue by FactorioTrainwreck** [KiwiHawk/SeaBlock#1]
I don't have the time to work on mods at the moment, but thanks for taking interest and keeping them up to date. I do intend to get back into modding at some point, no idea when that will be though.

If you want to be the official maintainer just let me know and I'll add you as a collaborator on the mod portal.

**Comment by KiwiHawk** [comment]
Thank you for your work making these mods! It's greatly appreciated. I'm glad that I was able to get in contact with you.

Yes, if you could add me as a collaborator for your mods that would be great thanks! I'd definitely prefer to keep it "official" rather than having forked mod versions.

I've also created a repository for Circuit Processing and will for Landfill Painting too.
https://github.com/KiwiHawk/CircuitProcessing

**Comment by FactorioTrainwreck** [comment]
Done. Have fun :)
