### ISSUE TITLE
Adding exact mod versions to Sea Block Meta Pack

### ISSUE THREAD

**Issue by KiwiHawk** [KiwiHawk/SeaBlock#56]
Test how the in game mod manager handles this. What if newer versions are available? Installed? Will mods update to the specified version? Or the latest

**Comment by jodokus31** [comment]
I once made a proposal in factorio forum, which might be interesting:
https://forums.factorio.com/viewtopic.php?f=6&t=93819

**Comment by KiwiHawk** [comment]
That would be a useful step in the right direction. I've thought about making a post about mod packs at some stage. Still getting my ideas straight. I'd like this plus additional support for mod packs:

1. Only one mod pack should be installable at a time. If you have a mod pack enabled, the mods would install to a separate directory. It's the mod pack developer's job to prevent dependency hell.
2. Ability to specify categories of mods, within the pack.

For Sea Block the categories would be:
- Core mods. (Sea Block mod and it's dependencies)
- Highly Recommended. These come as standard but can be removed if you want. (SCT, Circuit Processing. Most of Bob's mods)
- Nice to have (KS Power, Bob's mining)
- Additional challenge. Doesn't make much difference if you remove. (SpaceX)
- Graphical (Landfill Painting, and I'd add Artisanal Reskins)
- Helper (FNEI and Helmod, with option for players to use Recipe Book or Factory Planner if they prefer)

I wouldn't specify versions for Graphical or Helper mods.

**Comment by jodokus31** [comment]
I have the suspicion, the "one mod pack at a time" proposal won't be heard by the devs, because the sync mods feature is a different approach, which explicitly allows switching of mod combinations.
However, if you would have a user friendly front-end to the "--mod-directory" command line option, where you could switch between modpacks, it could work.

The mod categories inside the pack sounds cool. Personally, i wouldn't allow to much combinations, which can each fail individually. Esp. if they destroy the balance (f.e. removing SCT and Circuit Processing is a very different game)

**Comment by KiwiHawk** [comment]
These combinations are all supported by Sea Block currently! I have thought about making more of the mods required. It would make testing and maintenance a bit easier ...

**Comment by jodokus31** [comment]
For me, the modpack currently is the zip-file, which contains all recommended mods with correct versions. It's possible to deviate and update, remove and add mods, but its more at one's own risk. If something's failing, you can point to recommended mods incl. versions.
If you want to really support more combinations, it will be more time-consuming.
Helper mods are probably an exception.

It's also helpful to install a separate factorio instance via zip-version of factorio. This has two major advantages:
- Your base game can stay on the version forever without steam to make forced updates.
- Your installed mods and settings don't interfere with other factorio experiences.

Maybe, there should be a instruction page somwhere, how to setup seablock properly, unless its already existing..

**Comment by ickputzdirwech** [comment]
I solely use the in game mod portal to enable, disable and update mods and in rare cases select specific versions of them (for the last case I might download a specific version on the mod portal website). Downloading the zip version of the mod pack from the forums is a hacky, for some people inaccessible workaround that originates from times when the in game mod portal didn't exist in the current form (my opinion). It is certainly not the intended way to install mods any more. I think it's therefore quite important to give people an easy way to enable the full mod pack (by setting hard dependencies) and a clear guide line which mods are recommended (optional dependencies). Mods that are supposed to be compatible but are not actually recommended should be hidden dependencies.

This is my suggestion which mods should be a dependency of which mod (taken from another issue on this board - where it was quite of topic now that I look at it now - and adjusted for the terminology in this issue):

SeaBlock:

- hard dependency: "required"
- optional dependency: "recommended"
- hidden optional dependency (when necessary): "nice to have", "additional challenge", "graphical" and "helpers"

SeaBlockMetaPack:

- hard dependency: "required", "recommended", "nice to have" and "additional challenge"
- optional dependency: "graphical" and "helpers"

Leaving the version empty or setting it to the oldest compatible version (that wouldn't crash) is certainly the most flexible solution, it's not the user friendliest however. I would suggest to always set it to the most recent tested compatible version. Otherwise people don't know when it is save to update their mods.

In case of game breaking changes that would require to rebuild huge parts of a base people could decide to not update the pack, instead of having to decide to not updating a specific mod (and in worst case having to read 10+ changelogs to make an educated decision).

> Maybe, there should be a instruction page somwhere, how to setup seablock properly, unless its already existing..

KiwiHawk linked this work-in-progress description in the aforementioned discussion: https://seablock.fandom.com/wiki/Sea_Block_Pack_Mods
